// Generated by Wrangler on Thu Jun 27 2024 17:31:00 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	SHEET_API_KEY: string;
	SHEET_ID: string;
	SYNC_TOKEN: string;
	GOOGLE_PRIVATE_KEY: string;
	GOOGLE_CLIENT_EMAIL: string;
	GOOGLE_TOKEN_URI: string;
	DB: D1Database;
}
