// Generated by Wrangler on Fri Jun 28 2024 15:26:04 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	GKEY_KV_NAMESPACE: KVNamespace;
	SHEET_API_KEY: string;
	SHEET_ID: string;
	SYNC_TOKEN: string;
	GOOGLE_PRIVATE_KEY: string;
	GOOGLE_CLIENT_EMAIL: string;
	GOOGLE_TOKEN_URI: string;
	DB: D1Database;
}
